---
layout: Resume
title: Emmanuel Kissi's Resume
---
# Emmanuel Kissi
Student, Financial Analyst, and Entrepreneur

<div id="webaddress">
<a href="mailto:kis20001@byui.edu">kis20001@byui.edu</a>
| <a href="https://linkedin.com/in/emmanuel-tabi-kissi">My LinkedIn</a>
</div>


## Currently

Business Intelligence Operations Analyst at Goldman Sachs

### Specialized in

Asset Management, Wealth Management, Investment Banking, Data Analytics, and Global Banking & Market.


### Research interests

Data governance, Financial modeling, Operational optimization, and Innovative data solutions.


## Education

`April 2021 - April 2025`  
__Brigham Young University - Idaho__, Rexburg, Idaho  

- Bachelor of Science in Business Analytics  
- Minor: Finance  
- Overall GPA: 3.95/4.00  
- Scholarships: Brigham Young University-Idaho Grant 2021-2025 (Acknowledgment of Academic Excellence)  


## Professional Experience

`June 2024 - Present`  
__Goldman Sachs__, Salt Lake City, Utah  
- Utilized Alteryx to automate workflows, decreasing manual data entry by 40% and enhancing operational efficiency.  
- Developed interactive Tableau dashboards, driving real-time insights and improving decision-making for senior management.  
- Implemented data governance measures, reducing discrepancies by 30% and ensuring compliance with industry standards.  

`January 2022 - Present`  
__Kissi Shuttle Services__, Kumasi, Ghana  
- Established a shuttle business with 7 vehicles, achieving a 20% annual revenue increase and reducing costs by 15%.  
- Executed marketing strategies, including digital campaigns, resulting in a 65% expansion of the customer base.  
- Supervised 15 employees, fostering productivity, excellent customer service, and a positive work environment.  

`September 2022 - May 2024`  
__Career Success Mentor, Brigham Young University - Idaho__, Rexburg, Idaho  
- Mentored 227 students, leading to 189 securing job offers.  
- Achieved a 98.5% satisfaction rating through constructive feedback and personalized coaching.  
- Stayed abreast of job market trends to offer relevant coaching strategies.  

`January 2023 - April 2023`  
__Financial Analyst, The Church of Jesus Christ of Latter-Day Saints__, Salt Lake City, Utah  
- Analyzed over 10,000 receipts to ensure compliance with financial controls.  
- Processed 100+ invoices, ensuring timely and accurate payments.  
- Presented audit findings using Power BI and Tableau, enabling informed decision-making.  

---

## Key Skills

- **Data Analysis**: Microsoft Excel, Python, R, SQL, Pivot Tables.  
- **Business Intelligence Tools**: Tableau, Alteryx, Power BI.  
- **Financial Tools**: QuickBooks, IAN.  
- **Soft Skills**: Teamwork, Leadership, Communication, Time Management.  

---

## Publications and Awards

`2021-2025`  
Brigham Young University-Idaho Grant – Awarded for Academic Excellence.

---

Last updated: December 2024